
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.ReportDao;
import Dao.PengadaanDao;
import Dao.PrediksiDao;
import Koneksi.Koneksi;
import Model.tb_model;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ariboss89
 */
public class FormPrediksi extends javax.swing.JFrame {

    PengadaanDao pd = new PengadaanDao();
    tb_model tbm = new tb_model();
    String[][] res;
    String[] namaKolom = {"ID", "BULAN", "TAHUN", "JUMLAH", "MOTIF"};
    int jmlKolom = namaKolom.length;
    int[] lebar = {200, 500, 700, 200, 400};
    Koneksi con;
    Statement st;
    ResultSet rs;
    ReportDao rd = new ReportDao();
    PrediksiDao prd = new PrediksiDao();

    public FormPrediksi() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (dim.width - getWidth()) / 2;
        int y = (dim.height - getHeight()) / 2;
        setLocation(x, y);
        Refresh();
        ShowBarang();
    }

    private void Refresh() {
        prd.IdRiwayat();
    }

    void ShowBarang(){
        con = new Koneksi();
        try{
            st = con.connect().createStatement();
            rs = st.executeQuery("SELECT *FROM tb_barang");
            while(rs.next()){
                cbBarang.addItem(rs.getString("nama_barang"));
            }
        }catch(SQLException e){
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNilaiErrorTerkecil = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtNilaiAlpha = new javax.swing.JTextField();
        txtHasilPrediksi = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtMSE = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        txtError1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtError2 = new javax.swing.JTextField();
        txtError3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtError4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtError5 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtError6 = new javax.swing.JTextField();
        txtError7 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtError8 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtError9 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbDariTahun = new javax.swing.JComboBox<>();
        cbSampaiTahun = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbBarang = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(153, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("NILAI ERROR TERKECIL");

        txtNilaiErrorTerkecil.setEditable(false);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("PREDIKSI");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("NILAI ALPHA");

        txtNilaiAlpha.setEditable(false);

        txtHasilPrediksi.setEditable(false);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("TINGKAT AKURASI");

        txtMSE.setEditable(false);

        jButton2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jButton2.setText("CETAK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("HASIL PERHITUNGAN");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(451, 451, 451))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNilaiAlpha)
                            .addComponent(txtNilaiErrorTerkecil)
                            .addComponent(txtHasilPrediksi, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMSE, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNilaiErrorTerkecil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNilaiAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHasilPrediksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMSE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(229, 229, 229))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("PARAMETER 0.1");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("PARAMETER 0.2");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jTable4);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("PARAMETER 0.3");

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(jTable5);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("PARAMETER 0.4");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("PARAMETER 0.5");

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(jTable6);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("PARAMETER 0.6");

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane8.setViewportView(jTable7);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("PARAMETER 0.7");

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane9.setViewportView(jTable8);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("PARAMETER 0.8");

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane10.setViewportView(jTable9);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("PARAMETER 0.9");

        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane11.setViewportView(jTable10);

        txtError1.setEditable(false);
        txtError1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtError1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("JUMLAH ERROR");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("JUMLAH ERROR");

        txtError2.setEditable(false);

        txtError3.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("JUMLAH ERROR");

        txtError4.setEditable(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("JUMLAH ERROR");

        txtError5.setEditable(false);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("JUMLAH ERROR");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("JUMLAH ERROR");

        txtError6.setEditable(false);

        txtError7.setEditable(false);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("JUMLAH ERROR");

        txtError8.setEditable(false);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("JUMLAH ERROR");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("JUMLAH ERROR");

        txtError9.setEditable(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtError9, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtError2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtError1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtError4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtError3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtError6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtError5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtError8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtError7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtError1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtError2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addComponent(jLabel5))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtError3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addComponent(jLabel6))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtError4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addComponent(jLabel7))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtError5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17))
                    .addComponent(jLabel8))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtError6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18))
                    .addComponent(jLabel9))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtError7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19))
                    .addComponent(jLabel10))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtError8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20))
                    .addComponent(jLabel11))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtError9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21))
                    .addComponent(jLabel12))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane3.setViewportView(jPanel7);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("PREDIKSI DENGAN SES");

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel2.setText("DARI TAHUN");

        cbDariTahun.setFont(new java.awt.Font("Yu Gothic Medium", 1, 11)); // NOI18N
        cbDariTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        cbSampaiTahun.setFont(new java.awt.Font("Yu Gothic Medium", 1, 11)); // NOI18N
        cbSampaiTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        jLabel25.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel25.setText("SAMPAI TAHUN");

        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel4.setText("BARANG");

        cbBarang.setFont(new java.awt.Font("Yu Gothic Medium", 1, 11)); // NOI18N
        cbBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH" }));
        cbBarang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbBarangItemStateChanged(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("PREDIKSI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbSampaiTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbDariTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDariTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(cbSampaiTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        Date tanggal = Date.valueOf(java.time.LocalDate.now());

        String tgl = formatter.format(tanggal);
        String namaBarang = cbBarang.getSelectedItem().toString();
        String dari = cbDariTahun.getSelectedItem().toString();
        String sampai = cbSampaiTahun.getSelectedItem().toString();
        String nilaiAlpha = txtNilaiAlpha.getText().trim();
        String akurasi = txtMSE.getText().trim()+"%";
        String hasil = txtHasilPrediksi.getText().trim();
        String idRiwayat = prd.IdRiwayat();

        rd.CetakHasil(tgl, idRiwayat, dari, sampai, namaBarang, nilaiAlpha, akurasi, hasil);

        prd.Save(tgl, idRiwayat, dari, sampai, namaBarang, nilaiAlpha, akurasi, hasil);

        prd.SaveIdRiwayat(idRiwayat);
        
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtError1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtError1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtError1ActionPerformed

    private void cbBarangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbBarangItemStateChanged
        // TODO add your handling code here:
        res = pd.ShowByBarang(cbDariTahun.getSelectedItem().toString(),cbSampaiTahun.getSelectedItem().toString(), cbBarang.getSelectedItem().toString());
        tbm.SetTabel(jTable1, res, namaKolom, jmlKolom, lebar);
    }//GEN-LAST:event_cbBarangItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int count = jTable1.getRowCount();
        if(cbDariTahun.getSelectedIndex()==0 || cbSampaiTahun.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Silahkan Pilih Tahun !!");
        }
        else if(cbBarang.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Silahkan Pilih Barang !!");
        }
        else if(count <3){
            JOptionPane.showMessageDialog(null, "Data Minimal 3 !!");
        }else{
        
        Double shasil = 0.0;
        Double hasil = 0.0;
        Double hitung = 0.0;

        Double shasil2 = 0.0;
        Double hasil2 = 0.0;
        Double hitung2 = 0.0;

        Double shasil3 = 0.0;
        Double hasil3 = 0.0;
        Double hitung3 = 0.0;

        Double shasil4 = 0.0;
        Double hasil4 = 0.0;
        Double hitung4 = 0.0;

        Double shasil5 = 0.0;
        Double hasil5 = 0.0;
        Double hitung5 = 0.0;

        Double shasil6 = 0.0;
        Double hasil6 = 0.0;
        Double hitung6 = 0.0;

        Double shasil7 = 0.0;
        Double hasil7 = 0.0;
        Double hitung7 = 0.0;

        Double shasil8 = 0.0;
        Double hasil8 = 0.0;
        Double hitung8 = 0.0;

        Double shasil9 = 0.0;
        Double hasil9 = 0.0;
        Double hitung9 = 0.0;

        ArrayList<Double> listNilai = new ArrayList<Double>();
        ArrayList<Double> listJumlah = new ArrayList<Double>();

        String[] bulan = new String[count];
        String[] tahun = new String[count];
        Double[] jumlah = new Double[count];
        Double[] aktual = new Double[count];

        //1
        DefaultTableModel dataModel = (DefaultTableModel) jTable2.getModel();
        dataModel.addColumn("Bulan");
        dataModel.addColumn("Tahun");
        dataModel.addColumn("Jumlah Aktual");
        dataModel.addColumn("Hasil");

        //2
        DefaultTableModel dataModel2 = (DefaultTableModel) jTable3.getModel();
        dataModel2.addColumn("Bulan");
        dataModel2.addColumn("Tahun");
        dataModel2.addColumn("Jumlah Aktual");
        dataModel2.addColumn("Hasil");

        //3
        DefaultTableModel dataModel3 = (DefaultTableModel) jTable4.getModel();
        dataModel3.addColumn("Bulan");
        dataModel3.addColumn("Tahun");
        dataModel3.addColumn("Jumlah Aktual");
        dataModel3.addColumn("Hasil");

        //4
        DefaultTableModel dataModel4 = (DefaultTableModel) jTable5.getModel();
        dataModel4.addColumn("Bulan");
        dataModel4.addColumn("Tahun");
        dataModel4.addColumn("Jumlah Aktual");
        dataModel4.addColumn("Hasil");

        //5
        DefaultTableModel dataModel5 = (DefaultTableModel) jTable6.getModel();
        dataModel5.addColumn("Bulan");
        dataModel5.addColumn("Tahun");
        dataModel5.addColumn("Jumlah Aktual");
        dataModel5.addColumn("Hasil");

        //6
        DefaultTableModel dataModel6 = (DefaultTableModel) jTable7.getModel();
        dataModel6.addColumn("Bulan");
        dataModel6.addColumn("Tahun");
        dataModel6.addColumn("Jumlah Aktual");
        dataModel6.addColumn("Hasil");

        //7
        DefaultTableModel dataModel7 = (DefaultTableModel) jTable8.getModel();
        dataModel7.addColumn("Bulan");
        dataModel7.addColumn("Tahun");
        dataModel7.addColumn("Jumlah Aktual");
        dataModel7.addColumn("Hasil");

        //8
        DefaultTableModel dataModel8 = (DefaultTableModel) jTable9.getModel();
        dataModel8.addColumn("Bulan");
        dataModel8.addColumn("Tahun");
        dataModel8.addColumn("Jumlah Aktual");
        dataModel8.addColumn("Hasil");

        //9
        DefaultTableModel dataModel9 = (DefaultTableModel) jTable10.getModel();
        dataModel9.addColumn("Bulan");
        dataModel9.addColumn("Tahun");
        dataModel9.addColumn("Jumlah Aktual");
        dataModel9.addColumn("Hasil");

        int row = jTable1.getRowCount();
        int column = dataModel.getColumnCount();

        String[][] data = new String[row][5];
        String[][] data2 = new String[row][5];
        String[][] data3 = new String[row][5];
        String[][] data4 = new String[row][5];
        String[][] data5 = new String[row][5];
        String[][] data6 = new String[row][5];
        String[][] data7 = new String[row][5];
        String[][] data8 = new String[row][5];
        String[][] data9 = new String[row][5];

        for (int c = 0; c < column; c++) {

            for (int r = 0; r < row; r++) {

                Double nilai = Double.parseDouble(jTable1.getValueAt(r, 3).toString());
                data[r][c] = jTable1.getValueAt(r, c + 1).toString();
                data2[r][c] = jTable1.getValueAt(r, c + 1).toString();
                data3[r][c] = jTable1.getValueAt(r, c + 1).toString();
                data4[r][c] = jTable1.getValueAt(r, c + 1).toString();
                data5[r][c] = jTable1.getValueAt(r, c + 1).toString();
                data6[r][c] = jTable1.getValueAt(r, c + 1).toString();
                data7[r][c] = jTable1.getValueAt(r, c + 1).toString();
                data8[r][c] = jTable1.getValueAt(r, c + 1).toString();
                data9[r][c] = jTable1.getValueAt(r, c + 1).toString();

                if (c == 3) {
                    if(r == 0) {
                        shasil = nilai;
                        data[r][3] = shasil.toString();

                        shasil2 = nilai;
                        data2[r][3] = shasil2.toString();

                        shasil3 = nilai;
                        data3[r][3] = shasil3.toString();

                        shasil4 = nilai;
                        data4[r][3] = shasil4.toString();

                        shasil5 = nilai;
                        data5[r][3] = shasil5.toString();

                        shasil6 = nilai;
                        data6[r][3] = shasil6.toString();

                        shasil7 = nilai;
                        data7[r][3] = shasil7.toString();

                        shasil8 = nilai;
                        data8[r][3] = shasil8.toString();

                        shasil9 = nilai;
                        data9[r][3] = shasil9.toString();

                    } else if (r == 1) {
                        hasil = (0.1 * nilai) + ((1.0 - 0.1) * shasil);
                        data[r][3] = hasil.toString();

                        hasil2 = ((0.2 * nilai) + ((1.0 - 0.2) * shasil2));
                        data2[r][3] = hasil2.toString();

                        hasil3 = ((0.3 * nilai) + ((1.0 - 0.3) * shasil3));
                        data3[r][3] = hasil3.toString();

                        hasil4 = ((0.4 * nilai) + ((1.0 - 0.4) * shasil4));
                        data4[r][3] = hasil4.toString();

                        hasil5 = ((0.5 * nilai) + ((1.0 - 0.5) * shasil5));
                        data5[r][3] = hasil5.toString();

                        hasil6 = ((0.6 * nilai) + ((1.0 - 0.6) * shasil6));
                        data6[r][3] = hasil6.toString();

                        hasil7 = ((0.7 * nilai) + ((1.0 - 0.7) * shasil7));
                        data7[r][3] = hasil7.toString();

                        hasil8 = ((0.8 * nilai) + ((1.0 - 0.8) * shasil8));
                        data8[r][3] = hasil8.toString();

                        hasil9 = ((0.9 * nilai) + ((1.0 - 0.9) * shasil9));
                        data9[r][3] = hasil9.toString();

                    } else {
                        Double nilaix = Double.parseDouble(data[r - 1][3]);
                        Double nilaiy = Double.parseDouble(data2[r - 1][3]);

                        hitung = (0.1 * nilai) + ((1.0 - 0.1) * nilaix);
                        data[r][3] = hitung.toString();

                        hitung2 = ((0.2 * nilai) + ((1.0 - 0.2) * nilaiy));
                        data2[r][3] = hitung2.toString();

                        hitung3 = ((0.3 * nilai) + ((1.0 - 0.3) * nilaiy));
                        data3[r][3] = hitung3.toString();

                        hitung4 = ((0.4 * nilai) + ((1.0 - 0.4) * nilaiy));
                        data4[r][3] = hitung4.toString();

                        hitung5 = ((0.5 * nilai) + ((1.0 - 0.5) * nilaiy));
                        data5[r][3] = hitung5.toString();

                        hitung6 = ((0.6 * nilai) + ((1.0 - 0.6) * nilaiy));
                        data6[r][3] = hitung6.toString();

                        hitung7 = ((0.7 * nilai) + ((1.0 - 0.7) * nilaiy));
                        data7[r][3] = hitung7.toString();

                        hitung8 = ((0.8 * nilai) + ((1.0 - 0.8) * nilaiy));
                        data8[r][3] = hitung8.toString();

                        hitung9 = ((0.9 * nilai) + ((1.0 - 0.9) * nilaiy));
                        data9[r][3] = hitung9.toString();
                    }
                }

            }
        }

        dataModel.addColumn("MAE");
        dataModel2.addColumn("MAE");
        dataModel3.addColumn("MAE");
        dataModel4.addColumn("MAE");
        dataModel5.addColumn("MAE");
        dataModel6.addColumn("MAE");
        dataModel7.addColumn("MAE");
        dataModel8.addColumn("MAE");
        dataModel9.addColumn("MAE");
        Double MAE = 0.0;
        Double MAE2 = 0.0;
        Double MAE3 = 0.0;
        Double MAE4 = 0.0;
        Double MAE5 = 0.0;
        Double MAE6 = 0.0;
        Double MAE7 = 0.0;
        Double MAE8 = 0.0;
        Double MAE9 = 0.0;

        for (int ax = 0; ax < count; ax++) {
            Double nilai1 = Double.parseDouble(data[ax][2]);
            Double nilai2 = Double.parseDouble(data[ax][3]);

            Double nilai3 = Double.parseDouble(data2[ax][2]);
            Double nilai4 = Double.parseDouble(data2[ax][3]);

            Double nilai5 = Double.parseDouble(data3[ax][2]);
            Double nilai6 = Double.parseDouble(data3[ax][3]);

            Double nilai7 = Double.parseDouble(data4[ax][2]);
            Double nilai8 = Double.parseDouble(data4[ax][3]);

            Double nilai9 = Double.parseDouble(data5[ax][2]);
            Double nilai10 = Double.parseDouble(data5[ax][3]);

            Double nilai11 = Double.parseDouble(data6[ax][2]);
            Double nilai12 = Double.parseDouble(data6[ax][3]);

            Double nilai13 = Double.parseDouble(data7[ax][2]);
            Double nilai14 = Double.parseDouble(data7[ax][3]);

            Double nilai15 = Double.parseDouble(data8[ax][2]);
            Double nilai16 = Double.parseDouble(data8[ax][3]);

            Double nilai17 = Double.parseDouble(data9[ax][2]);
            Double nilai18 = Double.parseDouble(data9[ax][3]);

            if (nilai1 > nilai2) {
                MAE = nilai1 - nilai2;
            } else if (nilai2 > nilai1) {
                MAE = nilai2 - nilai1;
            }

            if (nilai3 > nilai4) {
                MAE2 = nilai3 - nilai4;
            } else if (nilai4 > nilai3) {
                MAE2 = nilai4 - nilai3;
            }

            if (nilai3 > nilai4) {
                MAE2 = nilai3 - nilai4;
            } else if (nilai4 > nilai3) {
                MAE2 = nilai4 - nilai3;
            }

            if (nilai5 > nilai6) {
                MAE3 = nilai5 - nilai6;
            } else if (nilai6 > nilai5) {
                MAE3 = nilai6 - nilai5;
            }

            if (nilai7 > nilai8) {
                MAE4 = nilai7 - nilai8;
            } else if (nilai8 > nilai7) {
                MAE4 = nilai8 - nilai7;
            }

            if (nilai9 > nilai10) {
                MAE5 = nilai9 - nilai10;
            } else if (nilai10 > nilai9) {
                MAE5 = nilai10 - nilai9;
            }

            if (nilai11 > nilai12) {
                MAE6 = nilai11 - nilai12;
            } else if (nilai12 > nilai11) {
                MAE6 = nilai12 - nilai11;
            }

            if (nilai13 > nilai14) {
                MAE7 = nilai13 - nilai14;
            } else if (nilai14 > nilai13) {
                MAE7 = nilai14 - nilai13;
            }

            if (nilai15 > nilai16) {
                MAE8 = nilai15 - nilai16;
            } else if (nilai16 > nilai15) {
                MAE8 = nilai16 - nilai15;
            }

            if (nilai17 > nilai18) {
                MAE9 = nilai17 - nilai18;
            } else if (nilai18 > nilai17) {
                MAE9 = nilai18 - nilai17;
            }

            data[ax][4] = MAE.toString();
            data2[ax][4] = MAE2.toString();
            data3[ax][4] = MAE3.toString();
            data4[ax][4] = MAE4.toString();
            data5[ax][4] = MAE5.toString();
            data6[ax][4] = MAE6.toString();
            data7[ax][4] = MAE7.toString();
            data8[ax][4] = MAE8.toString();
            data9[ax][4] = MAE9.toString();
        }

        for (int x = 0; x < data.length; x++) {
            String[] rowa = new String[data[x].length];
            String[] row2 = new String[data2[x].length];
            String[] row3 = new String[data3[x].length];
            String[] row4 = new String[data4[x].length];
            String[] row5 = new String[data5[x].length];
            String[] row6 = new String[data6[x].length];
            String[] row7 = new String[data7[x].length];
            String[] row8 = new String[data8[x].length];
            String[] row9 = new String[data9[x].length];

            for (int y = 0; y < data[x].length; y++) {
                rowa[y] = data[x][y];
                row2[y] = data2[x][y];
                row3[y] = data3[x][y];
                row4[y] = data4[x][y];
                row5[y] = data5[x][y];
                row6[y] = data6[x][y];
                row7[y] = data7[x][y];
                row8[y] = data8[x][y];
                row9[y] = data9[x][y];
            }

            dataModel.addRow(rowa);
            dataModel2.addRow(row2);
            dataModel3.addRow(row3);
            dataModel4.addRow(row4);
            dataModel5.addRow(row5);
            dataModel6.addRow(row6);
            dataModel7.addRow(row7);
            dataModel8.addRow(row8);
            dataModel9.addRow(row9);
        }

        Double sum = 0.0;
        Double sum2 = 0.0;
        Double sum3 = 0.0;
        Double sum4 = 0.0;
        Double sum5 = 0.0;
        Double sum6 = 0.0;
        Double sum7 = 0.0;
        Double sum8 = 0.0;
        Double sum9 = 0.0;

        for (int axx = 0; axx < count; axx++) {

            sum += Double.parseDouble(jTable2.getValueAt(axx, 4).toString());
            sum2 += Double.parseDouble(jTable3.getValueAt(axx, 4).toString());
            sum3 += Double.parseDouble(jTable4.getValueAt(axx, 4).toString());
            sum4 += Double.parseDouble(jTable5.getValueAt(axx, 4).toString());
            sum5 += Double.parseDouble(jTable6.getValueAt(axx, 4).toString());
            sum6 += Double.parseDouble(jTable7.getValueAt(axx, 4).toString());
            sum7 += Double.parseDouble(jTable8.getValueAt(axx, 4).toString());
            sum8 += Double.parseDouble(jTable9.getValueAt(axx, 4).toString());
            sum9 += Double.parseDouble(jTable10.getValueAt(axx, 4).toString());
        }

        txtError1.setText(String.valueOf(sum));
        txtError2.setText(String.valueOf(sum2));
        txtError3.setText(String.valueOf(sum3));
        txtError4.setText(String.valueOf(sum4));
        txtError5.setText(String.valueOf(sum5));
        txtError6.setText(String.valueOf(sum6));
        txtError7.setText(String.valueOf(sum7));
        txtError8.setText(String.valueOf(sum8));
        txtError9.setText(String.valueOf(sum9));

        Double[] arrayError = new Double[9];

        //cek error terkecil
        arrayError[0] = sum;
        arrayError[1] = sum2;
        arrayError[2] = sum3;
        arrayError[3] = sum4;
        arrayError[4] = sum5;
        arrayError[5] = sum6;
        arrayError[6] = sum7;
        arrayError[7] = sum8;
        arrayError[8] = sum9;

        Double max = arrayError[0];
        Double min = arrayError[0];

        for (int k = 0; k < arrayError.length; k++) {
            if (arrayError[k] >= max) {
                max = arrayError[k];
            } else if (arrayError[k] <= min) {
                min = arrayError[k];

            }
        }

        int tableId = 0;
        int countTbl = jTable9.getRowCount();

        Double nilaixy = 0.0;
        Double nilaiyz = 0.0;
        Double hasilxyz = 0.0;
        Double sumAktual = 0.0;
        Double sumPrediksi = 0.0;
        Double MSE = 0.0;
        Double last = 0.0;

        if (txtError1.getText().equals(min)) {
            txtNilaiAlpha.setText("0.1");
            tableId = 1;
            nilaixy = Double.parseDouble(jTable2.getValueAt(countTbl-1 ,2).toString());
            nilaiyz = Double.parseDouble(jTable2.getValueAt(countTbl-1 ,3).toString());
            hasilxyz = ((0.1*nilaixy)+((1-0.1)*nilaiyz));

            txtHasilPrediksi.setText(String.valueOf(String.format("%.2f", hasilxyz)));

            for(int b = 0; b<countTbl; b++){
                sumAktual+= Double.parseDouble(jTable2.getValueAt(b, 2).toString());

                sumPrediksi+= Double.parseDouble(jTable2.getValueAt(b, 3).toString());
            }

            MSE = (((sumAktual-sumPrediksi)*(sumAktual-sumPrediksi))/countTbl);
            last = MSE*100/100;

            txtMSE.setText(String.valueOf(String.format("%.2f",last)));

        } else if (txtError2.getText().equals(String.valueOf(min))) {
            txtNilaiAlpha.setText("0.2");
            tableId = 2;
            nilaixy = Double.parseDouble(jTable3.getValueAt(countTbl-1 ,2).toString());
            nilaiyz = Double.parseDouble(jTable3.getValueAt(countTbl-1 ,3).toString());
            hasilxyz = ((0.2*nilaixy)+((1-0.2)*nilaiyz));

            txtHasilPrediksi.setText(String.valueOf(String.format("%.2f",hasilxyz)));

            for(int b = 0; b<countTbl; b++){
                sumAktual+= Double.parseDouble(jTable3.getValueAt(b, 2).toString());

                sumPrediksi+= Double.parseDouble(jTable3.getValueAt(b, 3).toString());
            }

            MSE = (((sumAktual-sumPrediksi)*(sumAktual-sumPrediksi))/countTbl);
            last = MSE*100/100;

            txtMSE.setText(String.valueOf(String.format("%.2f",last)));

        } else if (txtError3.getText().equals(String.valueOf(min))) {
            txtNilaiAlpha.setText("0.3");
            tableId = 3;
            nilaixy = Double.parseDouble(jTable4.getValueAt(countTbl-1 ,2).toString());
            nilaiyz = Double.parseDouble(jTable4.getValueAt(countTbl-1 ,3).toString());
            hasilxyz = ((0.3*nilaixy)+((1-0.3)*nilaiyz));

            txtHasilPrediksi.setText(String.valueOf(String.format("%.2f",hasilxyz)));

            for(int b = 0; b<countTbl; b++){
                sumAktual+= Double.parseDouble(jTable4.getValueAt(b, 2).toString());

                sumPrediksi+= Double.parseDouble(jTable4.getValueAt(b, 3).toString());
            }

            MSE = (((sumAktual-sumPrediksi)*(sumAktual-sumPrediksi))/countTbl);
            last = MSE*100/100;

            txtMSE.setText(String.valueOf(String.format("%.2f",last)));

        } else if (txtError4.getText().equals(String.valueOf(min))) {
            txtNilaiAlpha.setText("0.4");
            tableId = 4;
            nilaixy = Double.parseDouble(jTable5.getValueAt(countTbl-1 ,2).toString());
            nilaiyz = Double.parseDouble(jTable5.getValueAt(countTbl-1 ,3).toString());
            hasilxyz = ((0.4*nilaixy)+((1-0.4)*nilaiyz));

            txtHasilPrediksi.setText(String.valueOf(String.format("%.2f",hasilxyz)));

            for(int b = 0; b<countTbl; b++){
                sumAktual+= Double.parseDouble(jTable5.getValueAt(b, 2).toString());

                sumPrediksi+= Double.parseDouble(jTable5.getValueAt(b, 3).toString());
            }

            MSE = (((sumAktual-sumPrediksi)*(sumAktual-sumPrediksi))/countTbl);
            last = MSE*100/100;

            txtMSE.setText(String.valueOf(String.format("%.2f",last)));
        } else if (txtError5.getText().equals(String.valueOf(min))) {
            txtNilaiAlpha.setText("0.5");
            tableId = 5;
            nilaixy = Double.parseDouble(jTable6.getValueAt(countTbl-1 ,2).toString());
            nilaiyz = Double.parseDouble(jTable6.getValueAt(countTbl-1 ,3).toString());
            hasilxyz = ((0.5*nilaixy)+((1-0.5)*nilaiyz));

            txtHasilPrediksi.setText(String.valueOf(String.format("%.2f",hasilxyz)));

            for(int b = 0; b<countTbl; b++){
                sumAktual+= Double.parseDouble(jTable6.getValueAt(b, 2).toString());

                sumPrediksi+= Double.parseDouble(jTable6.getValueAt(b, 3).toString());
            }

            MSE = (((sumAktual-sumPrediksi)*(sumAktual-sumPrediksi))/countTbl);
            last = MSE*100/100;

            txtMSE.setText(String.valueOf(String.format("%.2f",last)));

        } else if (txtError6.getText().equals(String.valueOf(min))) {
            txtNilaiAlpha.setText("0.6");
            tableId = 6;
            nilaixy = Double.parseDouble(jTable7.getValueAt(countTbl-1 ,2).toString());
            nilaiyz = Double.parseDouble(jTable7.getValueAt(countTbl-1 ,3).toString());
            hasilxyz = ((0.6*nilaixy)+((1-0.6)*nilaiyz));

            txtHasilPrediksi.setText(String.valueOf(String.format("%.2f",hasilxyz)));

            for(int b = 0; b<countTbl; b++){
                sumAktual+= Double.parseDouble(jTable7.getValueAt(b, 2).toString());

                sumPrediksi+= Double.parseDouble(jTable7.getValueAt(b, 3).toString());
            }

            MSE = (((sumAktual-sumPrediksi)*(sumAktual-sumPrediksi))/countTbl);
            last = MSE*100/100;

            txtMSE.setText(String.valueOf(String.format("%.2f",last)));
        } else if (txtError7.getText().equals(String.valueOf(min))) {
            txtNilaiAlpha.setText("0.7");
            tableId = 7;
            nilaixy = Double.parseDouble(jTable8.getValueAt(countTbl-1 ,2).toString());
            nilaiyz = Double.parseDouble(jTable8.getValueAt(countTbl-1 ,3).toString());
            hasilxyz = ((0.7*nilaixy)+((1-0.7)*nilaiyz));

            txtHasilPrediksi.setText(String.valueOf(String.format("%.2f",hasilxyz)));

            for(int b = 0; b<countTbl; b++){
                sumAktual+= Double.parseDouble(jTable8.getValueAt(b, 2).toString());

                sumPrediksi+= Double.parseDouble(jTable8.getValueAt(b, 3).toString());
            }

            MSE = (((sumAktual-sumPrediksi)*(sumAktual-sumPrediksi))/countTbl);
            last = MSE*100/100;

            txtMSE.setText(String.valueOf(String.format("%.2f", last)));
        } else if (txtError8.getText().equals(String.valueOf(min))) {
            txtNilaiAlpha.setText("0.8");
            tableId = 8;
            nilaixy = Double.parseDouble(jTable9.getValueAt(countTbl-1 ,2).toString());
            nilaiyz = Double.parseDouble(jTable9.getValueAt(countTbl-1 ,3).toString());
            hasilxyz = ((0.8*nilaixy)+((1-0.8)*nilaiyz));

            txtHasilPrediksi.setText(String.valueOf(String.format("%.2f", hasilxyz)));

            for(int b = 0; b<countTbl; b++){
                sumAktual+= Double.parseDouble(jTable9.getValueAt(b, 2).toString());

                sumPrediksi+= Double.parseDouble(jTable9.getValueAt(b, 3).toString());
            }

            MSE = (((sumAktual-sumPrediksi)*(sumAktual-sumPrediksi))/countTbl);
            last = MSE*100/100;

            txtMSE.setText(String.valueOf(String.format("%.2f",last)));

        } else if (txtError9.getText().equals(String.valueOf(min))) {
            txtNilaiAlpha.setText("0.9");
            tableId = 9;

            nilaixy = Double.parseDouble(jTable10.getValueAt(countTbl-1 ,2).toString());
            nilaiyz = Double.parseDouble(jTable10.getValueAt(countTbl-1 ,3).toString());
            hasilxyz = ((0.9*nilaixy)+((1-0.9)*nilaiyz));

            txtHasilPrediksi.setText(String.valueOf(String.format("%.2f",hasilxyz)));

            for(int b = 0; b<countTbl; b++){
                sumAktual+= Double.parseDouble(jTable10.getValueAt(b, 2).toString());

                sumPrediksi+= Double.parseDouble(jTable10.getValueAt(b, 3).toString());
            }

            MSE = (((sumAktual-sumPrediksi)*(sumAktual-sumPrediksi))/countTbl);
            last = MSE*100/100;

            txtMSE.setText(String.valueOf(String.format("%.2f",last)));
        }

        txtNilaiErrorTerkecil.setText(String.valueOf(String.format("%.2f", min)));
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrediksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrediksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrediksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrediksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrediksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbBarang;
    private javax.swing.JComboBox<String> cbDariTahun;
    private javax.swing.JComboBox<String> cbSampaiTahun;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    private javax.swing.JTextField txtError1;
    private javax.swing.JTextField txtError2;
    private javax.swing.JTextField txtError3;
    private javax.swing.JTextField txtError4;
    private javax.swing.JTextField txtError5;
    private javax.swing.JTextField txtError6;
    private javax.swing.JTextField txtError7;
    private javax.swing.JTextField txtError8;
    private javax.swing.JTextField txtError9;
    private javax.swing.JTextField txtHasilPrediksi;
    private javax.swing.JTextField txtMSE;
    private javax.swing.JTextField txtNilaiAlpha;
    private javax.swing.JTextField txtNilaiErrorTerkecil;
    // End of variables declaration//GEN-END:variables
}
